export const SITE_URL = "https://launchsiteph.com"
export const SITE_NAME = "LaunchSite PH"
export const BUSINESS_EMAIL = "booksage.alex4@gmail.com"
export const BUSINESS_MOBILE_DISPLAY = "+63 991 439 3060"
export const BUSINESS_MOBILE_TEL = "+639914393060"
